/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ac_ict_htc_utils_NativeUtils */

#ifndef _Included_cn_ac_ict_htc_utils_NativeUtils
#define _Included_cn_ac_ict_htc_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_LOOPBACK
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_LOOPBACK 0L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_INIT_CPU
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_INIT_CPU 1L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_INIT_GPU
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_INIT_GPU 101L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_PUT_OFF
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_PUT_OFF 2L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_PUT_DATA
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_PUT_DATA 3L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_CALC
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_CALC 4L
#undef cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_FREE_MEM
#define cn_ac_ict_htc_utils_NativeUtils_CMD_CODE_FREE_MEM 13L
#undef cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_OK
#define cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_OK 0L
#undef cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_CONTINUE
#define cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_CONTINUE 1L
#undef cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_ERR
#define cn_ac_ict_htc_utils_NativeUtils_ERR_CODE_ERR -1L
/*
 * Class:     cn_ac_ict_htc_utils_NativeUtils
 * Method:    callNative
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_ac_ict_htc_utils_NativeUtils_callNative
  (JNIEnv *, jclass, jint, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
